title: Adaptation Gardening Crop Guides
description: An open repository of crop information from seed to plate
theme: just-the-docs

url: https://adaptation-gardening.github.io
#baseurl: crop-guides # needed when the pages are served from a subfolder, like on github.io
repository: adaptation-gardening/crop-guides # for github-metadata

permalink: pretty
nav_sort: case_insensitive

aux_links:
  "Crop Guides on GitHub":
    - "https://github.com/adaptation-gardening/crop-guides"

nav_external_links:
  - title: Going to Seed Courses and Community
    url: https://goingtoseed.org
  - title: Adaptation Gardening Facebook Group
    url: https://www.facebook.com/groups/adaptationagriculture

search_enabled: true

# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/images/crop-guide-logo-500x280.png"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/adaptation-gardening/crop-guides" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: adaptation-colors

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: purple
  idea:
    title: Idea
    color: blue
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: red
